spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
  flyway:
    enabled: true
    schemas: public
    sql-migration-separator: __
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/db
    locations: classpath:/db
